### ISSUE TITLE
Feature: User can generate images

### ISSUE THREAD

**Issue by JoshuaBeh** [JoshuaBeh/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can generate images.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to choose 1 of 3 sizes for the image and generate it based off the prompt that they typed in.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/113414352/220437243-fc7b3d59-bc28-4925-b9df-5f9c54d60e1e.png)
![image](https://user-images.githubusercontent.com/113414352/220437316-bddf77ae-2b02-445c-a590-ecef12e53e63.png)
![image](https://user-images.githubusercontent.com/113414352/220437400-e8607c94-6b47-4947-9553-08100bedda8e.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [ ] Update `server/index.js` to take the prompt and size given by the user and generate the image
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component for the nav-bar
- [ ] Create a component for the generate input and buttons
- [ ] Create a new view for the generated image
- [ ] Create a new component for the generated image that includes the generate again button

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
